title={

    'CUST_ID': 'CUSTOMER_ID',
    'CUSTOMER ID': 'CUSTOMER_ID',
    'CUSTOMERID': 'CUSTOMER_ID',
    'FIRSTNAME': 'FIRST_NAME',
    'FIRST NAME': 'FIRST_NAME',
    'LASTNAME': 'LAST_NAME',
    'LAST NAME': 'LAST_NAME',
    'SEX': 'GENDER',
    'SENIORCITIZEN': 'SENIOR_CITIZEN',
    'MARRIED': 'MARITAL_STATUS',
    'MARITAL STATUS': 'MARITAL_STATUS',
    'MARTIALSTATUS': 'MARITAL_STATUS',
    'DEPENDENCY': 'DEPENDENTS',
    'INCOME': 'MONTHLY_INCOME($)',
    'MONTHLY INCOME($)': 'MONTHLY_INCOME($)',
    'MONTHLY-INCOME($)': 'MONTHLY_INCOME($)',
    'MONTHLYINCOME($)': 'MONTHLY_INCOME($)',
    'CATEGORY': 'INCOME_CATEGORY',
    'INCOME CATEGORY': 'INCOME_CATEGORY',
    'INCOME-CATEGORY': 'INCOME_CATEGORY',
    'INCOMECATEGORY': 'INCOME_CATEGORY',
    'STATUS_CATEGORY': 'INCOME_CATEGORY',
    'STATUS CATEGORY': 'INCOME_CATEGORY',
    'STATUS-CATEGORY': 'INCOME_CATEGORY',
    'STATUSCATEGORY': 'INCOME_CATEGORY',
    'START DATE': 'JOIN_DATE',
    'START-DATE': 'JOIN_DATE',
    'STARTDATE': 'JOIN_DATE',
    'JOIN DATE': 'JOIN_DATE',
    'JOIN-DATE': 'JOIN_DATE',
    'JOINDATE': 'JOIN_DATE',
    'START_DATE': 'JOIN_DATE',
    'TENURE': 'TENURE_MONTHS',
    'TENURE MONTHS': 'TENURE_MONTHS',
    'PHONE':'PHONE_SERVICE',
    'PHONE SERVICE':'PHONE_SERVICE',
    'MULTI-LINE':'MULTIPLE_LINES',
    'MULTI LINE':'MULTIPLE_LINES',
    'MULTILINE':'MULTIPLE_LINES',
    'MULTIPLE LINES':'MULTIPLE_LINES',
    'INTERNET':'INTERNET_SERVICE',
    'INTERNET SERVICE':'INTERNET_SERVICE',
    'ONLINE SECURITY':'ONLINE_SECURITY',
    'BACKUP':'ONLINE_BACKUP',
    'ONLINE BACKUP':'ONLINE_BACKUP',
    'DEVICE PROTECTION':'DEVICE_PROTECTION',
    'TECH SUPPORT':'TECH_SUPPORT',
    'STREAMING TV':'TV_STREAMING',
    'STREAMING MOVIES':'MOVIE_STREAMING',
    'TV STREAMING':'TV_STREAMING',
    'MOVIE STREAMING':'MOVIE_STREAMING',
    'TV_STREAMING':'TV_STREAMING',
    'MOVIE_STREAMING':'MOVIE_STREAMING',
    'STREAMING_TV':'TV_STREAMING',
    'STREAMING_MOVIES':'MOVIE_STREAMING',   
    'PAYMENT METHOD':'PAYMENT_METHOD',
    'PAYMENT-METHOD':'PAYMENT_METHOD',
    'PAYMENT':'PAYMENT_METHOD',
    'CHURNED':'CHURN',
    'SALARY':'MONTHLY_INCOME($)',
    'SALARY($)':'MONTHLY_INCOME($)',
    'TOTALMONTHS':'TENURE_MONTHS',
    'TOTAL_MONTHS':'TENURE_MONTHS',
    'MONTHLYCHARGES':'MONTHLY_CHARGES($)',
    'MONTHLY_CHARGES':'MONTHLY_CHARGES($)',
    'TOTAL':'TOTAL_CHARGES($)',
    'TOTAL CHARGES':'TOTAL_CHARGES($)',
    'TOTALCHARGES':'TOTAL_CHARGES($)',
    'TOTALCHARGES($)':'TOTAL_CHARGES($)',
    'TOTAL_CHARGES':'TOTAL_CHARGES($)'
}

gender={
    'M': 'MALE',
    'F': 'FEMALE',
    'MAN':'MALE',
    'MEN':'MALE',
    'WOMAN':'FEMALE',
    'WOMEN':'FEMALE',
    'HE':'MALE',
    'SHE':'FEMALE',
}

senior_citizen={
    '1': 'YES',
    '0': 'NO',
    'Y': 'YES',
    'N': 'NO',
    '':'NO',
}

marital_status={
    'NOT MARRIED': 'SINGLE',
    'MARRIED': 'MARRIED',
}

Phone_service={
    '1': 'YES',
    '0': 'NO',
    'Y': 'YES',
    'N': 'NO',
    '':'NO',
}

multiple_lines={
    '1': 'YES',
    '0': 'NO',
    'Y': 'YES',
    'N': 'NO',
    '': 'NO',
    'NO PHONE':'NO PHONE SERVICE',
    'NOPHONE':'NO PHONE SERVICE',
    'NO-PHONE':'NO PHONE SERVICE',
}

internet_service={
    '':'NONE',
    'NULL':'NONE',
}

online_services={
    '':'NO',
    'NO INTERNET':'NO INTERNET SERVICE',
    'NOINTERNET':'NO INTERNET SERVICE',
    'NO-INTERNET':'NO INTERNET SERVICE',
    'NO INT':'NO INTERNET SERVICE',

}

contract={

'MONTHLY':'MONTH-TO-MONTH',
 'MONTHTOMONTH': 'MONTH-TO-MONTH',
 'MONTHTO MONTH': 'MONTH-TO-MONTH',
 'MONTH TOMONTH': 'MONTH-TO-MONTH',
 'MONTH-TOMONTH': 'MONTH-TO-MONTH',
 'MONTH TO MONTH': 'MONTH-TO-MONTH',
 'MONTHTO-MONTH': 'MONTH-TO-MONTH',
 '1Y': 'ONE YEAR',
 '1 YEAR': 'ONE YEAR',
 '1 Y':' ONE YEAR',
 'ONEYEAR':'ONE YEAR',
 '2Y':'TWO YEAR',
 '2 YEAR':'TWO YEAR',
 '2 Y':'TWO YEAR',


}

payment_method={
    'ECHECK':'ELECTRONIC CHECK',
    'E-CHECK':'ELECTRONIC CHECK',
}

churn={
    '1': 'YES',
    '0': 'NO',
    'Y': 'YES',
    'N': 'NO',
    '':'NO',
}